repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.5.0
        hooks:
        -   id: double-quote-string-fixer
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: mixed-line-ending
            args: ['--fix=lf']
        -   id: check-added-large-files
            args: ['--maxkb=15000']
    -   repo: git@github.com:humitos/mirrors-autoflake.git
        rev: v1.1
        hooks:
        - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
    -   repo: https://github.com/asottile/seed-isort-config
        rev: v1.9.3
        hooks:
        - id: seed-isort-config
    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v4.3.21
        hooks:
        - id: isort
    -   repo: git@github.com:myint/docformatter.git
        rev: v1.1
        hooks:
        - id: docformatter
        args: ['--in-place', '--wrap-summaries=80', '--wrap-descriptions=80', '--pre-summary-newline']
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.9
        hooks:
        - id: flake8
